

server:
  port: 8080

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  config:
    import: classpath:hidden.yml

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace



